### ISSUE TITLE
Calling paginate() returns error

### ISSUE THREAD

**Issue by leekaiwei** [jenssegers/laravel-mongodb#10]
Doing `User::paginate(1)` generates stack trace:

```
[2013-07-29 08:36:57] log.ERROR: exception 'ErrorException' with message 'Undefined index: result' in /var/www/leaf.dev/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Builder.php:129
Stack trace:
#0 /var/www/leaf.dev/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Builder.php(129): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/leaf.d...', 129, Array)
#1 /var/www/leaf.dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(943): Jenssegers\Mongodb\Builder->getFresh(Array)
#2 /var/www/leaf.dev/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Builder.php(192): Illuminate\Database\Query\Builder->get(Array)
#3 /var/www/leaf.dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1225): Jenssegers\Mongodb\Builder->aggregate('count', Array)
#4 /var/www/leaf.dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1195): Illuminate\Database\Query\Builder->count()
#5 /var/www/leaf.dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(213): Illuminate\Database\Query\Builder->getPaginationCount()
#6 /var/www/leaf.dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(184): Illuminate\Database\Eloquent\Builder->ungroupedPaginate(Object(Illuminate\Pagination\Environment), 20, Array)
#7 /var/www/leaf.dev/app/library/ArticleAPI.php(99): Illuminate\Database\Eloquent\Builder->paginate(20)
#8 /var/www/leaf.dev/app/controllers/ArticleController.php(36): app\library\ArticleAPI->latestArticles()
#9 [internal function]: ArticleController->getLatestArticles()
#10 /var/www/leaf.dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#11 /var/www/leaf.dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getLatestArticl...', Array)
#12 /var/www/leaf.dev/bootstrap/compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getLatestArticl...', Array)
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#14 /var/www/leaf.dev/bootstrap/compiled.php(7838): call_user_func_array(Object(Closure), Array)
#15 /var/www/leaf.dev/bootstrap/compiled.php(7825): Illuminate\Routing\Route->callCallable()
#16 /var/www/leaf.dev/bootstrap/compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 /var/www/leaf.dev/bootstrap/compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#18 /var/www/leaf.dev/bootstrap/compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#19 /var/www/leaf.dev/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []
```

**Comment by khungdisan** [comment]
How to conver to array when use pagination.
