### ISSUE TITLE
Select fails with "Call to a member function prepare() on null"

### ISSUE THREAD

**Issue by innobrig** [jenssegers/laravel-mongodb#1613]
Note: I'm editing this issue, the original title is incorrect. Please see below for details.

I am using your package outside of laravel and can't get it to work. I've attached a minimal test case which illustrates plain Mongdb access working and shows it failing when using your package. 

The error I'm getting is this: 

    PHP Fatal error:  Uncaught Error: Call to a member function all() on array in /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Builder.php:516
    Stack trace: 
    #0 /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Builder.php(500): Illuminate\Database\Eloquent\Builder->getModels(Array)
    #1 /var/www/html/BoostG8/vendor/illuminate/support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->get()
    #2 /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Model.php(1603): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Jenssegers\Mongodb\Eloquent\Builder), 'get', Array)
    #3 /var/www/html/BoostG8/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php(481): Illuminate\Database\Eloquent\Model->__call('get', Array)
    #4 /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Model.php(1615): Jenssegers\Mongodb\Eloquent\Model->__call('get', Array)
    #5 /var/www/html/BoostG8/mongoEloquent.php(49): Illuminate\Database\Eloquent\Model::__callStatic('get', Array)
    #6 {main}
     thrown in /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Builder.php on line 516

    Fatal error: Uncaught Error: Call to a member function all() on array in /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Builder.php on line 516

    Error: Call to a member function all() on array in /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Builder.php on line 516

    Call Stack:
        0.0001     402736   1. {main}() /var/www/html/BoostG8/mongoEloquent.php:0
        0.0121    2671112   2. Illuminate\Database\Eloquent\Model::get() /var/www/html/BoostG8/mongoEloquent.php:49
        0.0121    2671168   3. Illuminate\Database\Eloquent\Model::__callStatic() /var/www/html/BoostG8/mongoEloquent.php:49
        0.0127    2762784   4. TestModel->get() /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Model.php:1615
        0.0127    2762840   5. TestModel->__call() /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Model.php:1615
        0.0127    2762840   6. TestModel->__call() /var/www/html/BoostG8/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php:481
        0.0190    4367240   7. TestModel->forwardCallTo() /var/www/html/BoostG8/vendor/illuminate/database/Eloquent/Model.php:1603

 A minimal test case is attached below.

For reference, I have the following illuminate components installed:

    illuminate/cache                       v5.7.5   The Illuminate Cache package.
    illuminate/container                   v5.7.5   The Illuminate Container package.
    illuminate/contracts                   v5.7.5   The Illuminate Contracts package.
    illuminate/database                    v5.7.5   The Illuminate Database package.
    illuminate/events                      v5.7.5   The Illuminate Events package.
    illuminate/filesystem                  v5.7.5   The Illuminate Filesystem package.
    illuminate/support                     v5.7.5   The Illuminate Support package.

[mongoEloquent.php.zip](https://github.com/jenssegers/laravel-mongodb/files/2416296/mongoEloquent.php.zip)

**Comment by innobrig** [comment]
I found https://github.com/jenssegers/laravel-mongodb/issues/1402 and pulling dev-master fixes the issue.
