### ISSUE TITLE
Failed to read 4 bytes: socket error or timeout

### ISSUE THREAD

**Issue by Jaykishanp** [jenssegers/laravel-mongodb#1744]
**Error Log**

```
 [2019-04-03 13:41:46] local.ERROR: Failed to send "findAndModify" command with database "products": Failed to read 4 bytes: socket error or timeout {"exception":"[object] (MongoDB\\Driver\\Exception\\ConnectionTimeoutException(code: 4): Failed to send \"findAndModify\" command with database \"awiproducts\": Failed to read 4 bytes: socket error or timeout at /var/www/html/vendor/mongodb/mongodb/src/Operation/FindAndModify.php:213)
[stacktrace]
#0 /var/www/html/vendor/mongodb/mongodb/src/Operation/FindAndModify.php(213): MongoDB\\Driver\\Server->executeWriteCommand('awiproducts', Object(MongoDB\\Driver\\Command), Array)
#1 /var/www/html/vendor/mongodb/mongodb/src/Operation/FindOneAndDelete.php(106): MongoDB\\Operation\\FindAndModify->execute(Object(MongoDB\\Driver\\Server))
#2 /var/www/html/vendor/mongodb/mongodb/src/Collection.php(689): MongoDB\\Operation\\FindOneAndDelete->execute(Object(MongoDB\\Driver\\Server))
#3 /var/www/html/vendor/enqueue/mongodb/MongodbSubscriptionConsumer.php(62): MongoDB\\Collection->findOneAndDelete(Array, Array)
#4 /var/www/html/vendor/enqueue/enqueue/Consumption/QueueConsumer.php(264): Enqueue\\Mongodb\\MongodbSubscriptionConsumer->consume(10)
#5 /var/www/html/vendor/enqueue/laravel-queue/src/Worker.php(65): Enqueue\\Consumption\\QueueConsumer->consume()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Enqueue\\LaravelQueue\\Worker->daemon('interopOptionPr...', 'optionpricejobs', Object(Illuminate\\Queue\\WorkerOptions))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('interopOptionPr...', 'optionpricejobs')
#8 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(580): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#14 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/html/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
```

I have around 18,00,000 entries in my collection for job. Whenever i tried to run queue using below command
`php artisan queue:work "connection_name" --queue="queue_name" --tries=1 --timeout=1`

it throws above error.

**i already checked mongodb status. It is running.**

**Also used timeout as said in documentation.**
`DB::collection('demo')->timeout(-1)->update($data,['upsert'=>true]);`

**JOB: FetchProductOptionPrice.php**

```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;
use App\ProductOptionPrice;

class FetchProductOptionPrice implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $option_price_uri;
    protected $product_id;
    protected $product_uuid;
    protected $option_id;
    protected $option_uuid;

    private $url = "api_url";


    public function __construct(String $option_price_uri, String $product_id, String $product_uuid, String $option_id, String $option_uuid)
    {
        $this->option_price_uri = $option_price_uri;
        $this->product_id = $product_id;
        $this->product_uuid = $product_uuid;
        $this->option_id = $option_id;
        $this->option_uuid = $option_uuid;
    }


    public function handle()
    {
        set_time_limit(0);
        $product_option_price_data = $this->requestData($this->option_price_uri . "?");
        if (isset($product_option_price_data['data'])) {
            $product_option_price_data = $product_option_price_data['data'];
            foreach ($product_option_price_data as $op_key => $op_value) {
               $data = new Array();
                foreach ($op_value as $t_key => $t_value) {
					$data[$t_key] = $t_value;
                }
		$data['product_id'] = $this->product_id;
		$data['product_uuid'] = $this->product_uuid;
		$data['option_id'] = $this->option_id;
		$data['option_uuid'] = $this->option_uuid;
		\DB::collection('demo')->timeout(-1)->update($data, ['upsert' => true]);
            }
        }
    }

    private function requestData($url)
    {
        $client = new Client();
        $qString = '';
        try {
            $result = $client->get($url . $qString);
            $data = json_decode($result->getBody()->getContents(), true);
        } catch (GuzzleException $ex) {
            $data = [];
        }
        return $data;
    }
}
```

**Comment by Jaykishanp** [comment]
I am able to resolve above using `use HybridRelations` in model where i am only using mongodb database. No other databases.

**Comment by louishong1127** [comment]
@jaykishan-kacha Hi, I am facing the problem recently.
Where did you put the trait 'HybridRelations' ?
I use DB::collection('users')..., not  User::find()..., I think HybridRelations will not be working when using DB.
