### ISSUE TITLE
Class MongoDB\Driver\Manager not found in cron schedule:run

### ISSUE THREAD

**Issue by sgimmai** [jenssegers/laravel-mongodb#1786]
**Laravel:** 5.8.18
**jenssegers/mongodb:** v3.5.1
**MongoDB shell version:** v4.0.10
**MongoDB server version:** 3.6.12
**PHP:** 7.1.30

Everything works fine when running `php artisan schedule:run` directly in the terminal.

However, the issue occurs when the the cron executes the `php artisan schedule:run`.
Here is my crontab `* * * * * cd /Users/sgimmai/Desktop/laravel-poi && php artisan schedule:run >/dev/null 2>&1`.

**Stack trace:**
```Class 'MongoDB\Driver\Manager' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'MongoDB\\Driver\\Manager' not found at /Users/sgimmai/Desktop/laravel-poi/vendor/mongodb/mongodb/src/Client.php:87)
[stacktrace]
#0 /Users/sgimmai/Desktop/laravel-poi/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php(149): MongoDB\\Client->__construct('mongodb://127.0...', Array, Array)
#1 /Users/sgimmai/Desktop/laravel-poi/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php(41): Jenssegers\\Mongodb\\Connection->createConnection('mongodb://127.0...', Array, Array)
#2 /Users/sgimmai/Desktop/laravel-poi/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/MongodbServiceProvider.php(30): Jenssegers\\Mongodb\\Connection->__construct(Array)
#3 [internal function]: Jenssegers\\Mongodb\\MongodbServiceProvider->Jenssegers\\Mongodb\\{closure}(Array, 'mongodb')
#4 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(120): call_user_func(Object(Closure), Array, 'mongodb')
#5 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(85): Illuminate\\Database\\DatabaseManager->makeConnection('mongodb')
#6 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Database\\DatabaseManager->connection('mongodb')
#7 /Users/sgimmai/Desktop/laravel-poi/packages/sgimmai/poi-middleware/src/console/commands/ProcessAuditTrail.php(78): Illuminate\\Support\\Facades\\Facade::__callStatic('connection', Array)
#8 [internal function]: Sgimmai\\POI\\Console\\Commands\\ProcessAuditTrail->handle()
#9 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#14 /Users/sgimmai/Desktop/laravel-poi/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /Users/sgimmai/Desktop/laravel-poi/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /Users/sgimmai/Desktop/laravel-poi/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Sgimmai\\POI\\Console\\Commands\\ProcessAuditTrail), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /Users/sgimmai/Desktop/laravel-poi/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /Users/sgimmai/Desktop/laravel-poi/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /Users/sgimmai/Desktop/laravel-poi/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"}

**Comment by Smolevich** [comment]
Are you sure that extension mongodb installed?

Show `php -m`

**Comment by sgimmai** [comment]
@Smolevich 
Yes. It works normally when manually running the `php artisan schedule:run` in the terminal. It only throws the error when it is ran using cron.
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
mongodb
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
phpdbg_webhelper
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by Smolevich** [comment]
Check in termninal output for command
`whereis php` and use absolute path in crontab, before copying run ` <abslute_path>/php -m` and check that extension mongodb is installed

**Comment by sgimmai** [comment]
`whereis php` --> `/usr/bin/php`
`/usr/bin/php -m` --> no mongodb (v7.1.23)
`/usr/local/Cellar/php@7.1/7.1.30/bin/php -m` --> with mongodb (v7.1.30)

I ended up including the path being used by apache
`/usr/local/Cellar/php@7.1/7.1.30/bin/php artisan schedule:run >/dev/null 2>&1`

This should work now. Thanks 👍

**Comment by Smolevich** [comment]
@sgimmai, Please, close issue
