### ISSUE TITLE
Reading UTCDateTime from before 1970 results in an exception.

### ISSUE THREAD

**Issue by DFurnes** [jenssegers/laravel-mongodb#2026]
- Laravel-mongodb Version: 3.6.3
- PHP Version: 7.3.15
- Database Driver & Version: v4.0.16

### Description:

Reading a date field with a value before January 1st 1970 results in a fatal exception:

```
ErrorException:  A non well formed numeric value encountered in vendor/nesbot/carbon/src/Carbon/Traits/Timestamp.php on line 50
```

### Steps to reproduce
Create a record with a pre-1970 date in a date-casted field (like `created_at`):

```js
db.users.insert({"email": "broken@example.com", "created_at": ISODate("1968-01-17T14:19:49.324Z")});
```

Then, try to read it as an Eloquent model:

```php
$user = User::where('email', 'broken@example.com')->first();

print $user->created_at; // <-- ErrorException!
```

### Expected behaviour
Dates, before or after 1970, should be correctly parsed into `Carbon` objects!

### Actual behaviour

When trying to read a record with an `UTCDateTime` before 1970, the millisecond timestamp will be formed incorrectly. This causes the following error when [trying to create the Carbon instance](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Eloquent/Model.php#L102):

```
ErrorException:  A non well formed numeric value encountered in vendor/nesbot/carbon/src/Carbon/Traits/Timestamp.php on line 50
```

This seems to be because, for dates prior to 1970, both the timestamp (from `U`) and the milliseconds (from `v`) are provided as negative numbers, and so when concatenated they don't make sense (e.g. `"-61724410-676"` for January 1st 1968 rather than `"-61724410676"`).

<details><summary><b>Logs</b>:</summary>

```
[2020-04-22 19:45:50] local.ERROR: A non well formed numeric value encountered {"exception":"[object] (ErrorException(code: 0): A non well formed numeric value encountered at vendor/nesbot/carbon/src/Carbon/Traits/Timestamp.php:50)
[stacktrace]
#0 vendor/nesbot/carbon/src/Carbon/Traits/Timestamp.php(50): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'A non well form...', '/home/vagrant/S...', 50, Array)
#1 vendor/laravel/framework/src/Illuminate/Support/DateFactory.php(217): Carbon\\Carbon::createFromTimestampMs('-61724410-676')
#2 vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Support\\DateFactory->__call('createFromTimes...', Array)
#3 vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php(102): Illuminate\\Support\\Facades\\Facade::__callStatic('createFromTimes...', Array)
#4 app/Models/Model.php(165): Jenssegers\\Mongodb\\Eloquent\\Model->asDateTime(Object(MongoDB\\BSON\\UTCDateTime))
#5 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(762): App\\Models\\Model->asDateTime(Object(MongoDB\\BSON\\UTCDateTime))
#6 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(507): Illuminate\\Database\\Eloquent\\Model->asDate(Object(MongoDB\\BSON\\UTCDateTime))
#7 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(357): Illuminate\\Database\\Eloquent\\Model->castAttribute('birthdate', Object(MongoDB\\BSON\\UTCDateTime))
#8 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(323): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('birthdate')
#9 vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php(151): Illuminate\\Database\\Eloquent\\Model->getAttribute('birthdate')
#10 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1525): Jenssegers\\Mongodb\\Eloquent\\Model->getAttribute('birthdate')
#11 app/Http/Transformers/Legacy/UserTransformer.php(37): Illuminate\\Database\\Eloquent\\Model->__get('birthdate')
#12 vendor/league/fractal/src/Scope.php(407): App\\Http\\Transformers\\Legacy\\UserTransformer->transform(Object(App\\Models\\User))
#13 vendor/league/fractal/src/Scope.php(346): League\\Fractal\\Scope->fireTransformer(Object(App\\Http\\Transformers\\Legacy\\UserTransformer), Object(App\\Models\\User))
#14 vendor/league/fractal/src/Scope.php(235): League\\Fractal\\Scope->executeResourceTransformers()
#15 app/Http/Controllers/Traits/TransformsResponses.php(33): League\\Fractal\\Scope->toArray()
#16 app/Http/Controllers/Traits/TransformsResponses.php(56): App\\Http\\Controllers\\Controller->transform(Object(League\\Fractal\\Resource\\Item), 200)
#17 app/Http/Controllers/Legacy/UserController.php(148): App\\Http\\Controllers\\Controller->item(Object(App\\Models\\User))
#18 [internal function]: App\\Http\\Controllers\\Legacy\\UserController->show('_id', '5ea05286d845374...')
#19 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#20 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('show', Array)
#21 vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Legacy\\UserController), 'show')
#22 vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#23 vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#24 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 app/Http/Middleware/RequireScope.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\RequireScope->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'user')
#27 vendor/dosomething/gateway/src/Server/Middleware/SetGuard.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): DoSomething\\Gateway\\Server\\Middleware\\SetGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#29 vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 app/Http/Middleware/ParseOAuthHeader.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ParseOAuthHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 app/Http/Middleware/LogMemoryUsage.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\LogMemoryUsage->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#58 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#59 public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
```

</details>

**Comment by Giacomo92** [comment]
Hi @DFurnes , 
There is not test for this case, so I have just created a pull request see #2027 . All test is successful. So I think you are not saving the date correctly.  

Try to share the dump of `$user` or a screen from the record from a db client.

**Comment by DFurnes** [comment]
Thanks so much for the quick response & test case! I think this one is a little tricky – the bug only appears for me when I'm working with dates that have milliseconds on them.

I'll push up a test case to demonstrate what I'm seeing.

**Comment by DFurnes** [comment]
I've added a test demonstrating the issue I'm running into in 90f73d2c9b2acd7afc9c9e761e35c188036ab538.

As you showed in #2027, this bug does not occur for dates that don't have have milliseconds on them – so definitely an edge case, but unfortunately one that I ran into earlier today! 😅

**Comment by Smolevich** [comment]
Today i release new version 3.6.4

**Comment by Giacomo92** [comment]
I saw the PR @DFurnes . Good job! Thanks

**Comment by DFurnes** [comment]
Thank you both for the quick responses & merge! Really appreciate it. 🙇

**Comment by Smolevich** [comment]
I released new version https://github.com/jenssegers/laravel-mongodb/releases/tag/v3.6.4
