### ISSUE TITLE
Failed to resolve 'mariadb'

### ISSUE THREAD

**Issue by beeards** [jenssegers/laravel-mongodb#2397]
- Laravel-mongodb Version: 3.9
- PHP Version: 8.1.6
- Database Driver & Version: 5.0.8

### Description:

I'm a newbie trying to configure CI/CD in Gitlab and run `php artisan migrate` in a .gitlab-ci.yml for a project based in Lumen & MongoDb via bitnami.

The code it's working fine in a local macOS PHP 8.1 & MongoDb 4.4.13 without Docker, but not in Docker bitnami/laravel.

### Steps to reproduce

`.Dockerfile`

```Dockerfile
FROM bitnami/laravel:latest
RUN apt-get update
RUN apt install -y wget gnupg2 lsb-release php-dev \
    && pecl channel-update pecl.php.net \
    && pecl install mongodb \
    && echo "extension=mongodb.so" >> /opt/bitnami/php/lib/php.ini
RUN wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add - \
    && echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list \
    && apt-get update \
    && apt-get install -y mongodb-org=5.0.8 mongodb-org-database=5.0.8 mongodb-org-server=5.0.8 mongodb-org-shell=5.0.8 mongodb-org-mongos=5.0.8 mongodb-org-tools=5.0.8
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /etc/apk/cache/*
```
`.gitlab-ci.yml` _Note: .Dockerfile is the container Pushed to Hub_

```yml
stages:
  - test
image: .Dockerfile
test:
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate
```

`.env.example`

```env
APP_NAME=Lumen
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost

DB_CONNECTION=mongodb
DB_HOST=127.0.0.1
DB_PORT=27017
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

`bootstrap/app.php`

```php
// ...
$app->withFacades();
$app->register(Jenssegers\Mongodb\MongodbServiceProvider::class);
$app->withEloquent();
// ...
```

`config/database.php`

```php
return [
    'default' => 'mongodb',
    'connections' => [
        'mongodb' => [
            'driver' => 'mongodb',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'options' => [
                'database' => env('DB_AUTHENTICATION_DATABASE', 'admin'),
            ]
        ],
    ],
    'migrations' => 'migrations',
];
```

`composer.json` _Note: require "jenssegers/mongodb"_

```json
{
    "...": "...",
    "require": {
        "php": "^8.0",

        "jenssegers/mongodb": "^3.9",

        "laravel/lumen-framework": "^9.0"
    },
    "...": "..."
}
```

`database/migrations/create_users_collection.php`

```php
use Illuminate\Database\Migrations\Migration;
//use Illuminate\Database\Schema\Blueprint;
use Jenssegers\Mongodb\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration
{
    protected $connection = 'mongodb';
    public function up()
    {
        Schema::create('users', function (Blueprint $collection) {
            $collection->unique(['email','username']);
        });
    }
}
```

### Expected behaviour

```sh
Migration table created successfully.
Migrating: create_users_collection
Migrated:  create_users_collection (18.20ms)
```

### Actual behaviour

Job test failed

```txt
...
$ php artisan migrate
In functions.php line 487:                         
  No suitable servers found (`serverSelectionTryOnce` set): [Failed to resolve 'mariadb']      
...
ERROR: Job failed: exit code 1                                                           
```

<details><summary><b>Logs</b>:</summary>

```txt
local.ERROR: No suitable servers found (`serverSelectionTryOnce` set): [Failed to resolve 'mariadb'] {"exception":"[object] (MongoDB\\Driver\\Exception\\ConnectionTimeoutException(code: 13053): No suitable servers found (`serverSelectionTryOnce` set): [Failed to resolve 'mariadb'] at /builds/_project_folder_/vendor/mongodb/mongodb/src/functions.php:487)
[stacktrace]
#0  /builds/_project_folder_/vendor/mongodb/mongodb/src/functions.php(487): MongoDB\\Driver\\Manager->selectServer()
#1  /builds/_project_folder_/vendor/mongodb/mongodb/src/Database.php(427): MongoDB\\select_server()
#2  /builds/_project_folder_/vendor/jenssegers/mongodb/src/Schema/Builder.php(157): MongoDB\\Database->listCollections()
#3  /builds/_project_folder_/vendor/jenssegers/mongodb/src/Schema/Builder.php(117): Jenssegers\\Mongodb\\Schema\\Builder->getAllCollections()
#4  /builds/_project_folder_/vendor/illuminate/database/Console/WipeCommand.php(82): Jenssegers\\Mongodb\\Schema\\Builder->dropAllTables()
#5  /builds/_project_folder_/vendor/illuminate/database/Console/WipeCommand.php(59): Illuminate\\Database\\Console\\WipeCommand->dropAllTables()
#6  /builds/_project_folder_/vendor/illuminate/container/BoundMethod.php(36): Illuminate\\Database\\Console\\WipeCommand->handle()
#7  /builds/_project_folder_/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8  /builds/_project_folder_/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9  /builds/_project_folder_/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /builds/_project_folder_/vendor/illuminate/container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#11 /builds/_project_folder_/vendor/illuminate/console/Command.php(136): Illuminate\\Container\\Container->call()
#12 /builds/_project_folder_/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#13 /builds/_project_folder_/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#14 /builds/_project_folder_/vendor/illuminate/console/Concerns/CallsCommands.php(68): Illuminate\\Console\\Command->run()
#15 /builds/_project_folder_/vendor/illuminate/console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#16 /builds/_project_folder_/vendor/illuminate/database/Console/Migrations/FreshCommand.php(43): Illuminate\\Console\\Command->call()
#17 /builds/_project_folder_/vendor/illuminate/container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\FreshCommand->handle()
#18 /builds/_project_folder_/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /builds/_project_folder_/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#20 /builds/_project_folder_/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#21 /builds/_project_folder_/vendor/illuminate/container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#22 /builds/_project_folder_/vendor/illuminate/console/Command.php(136): Illuminate\\Container\\Container->call()
#23 /builds/_project_folder_/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#24 /builds/_project_folder_/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#25 /builds/_project_folder_/vendor/symfony/console/Application.php(998): Illuminate\\Console\\Command->run()
#26 /builds/_project_folder_/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#27 /builds/_project_folder_/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#28 /builds/_project_folder_/vendor/illuminate/console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#29 /builds/_project_folder_/vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\\Console\\Application->run()
#30 /builds/_project_folder_/artisan(35): Laravel\\Lumen\\Console\\Kernel->handle()
#31 {main}
"} 
```

</details>

**Comment by beeards** [comment]
After digging more, I've seen in bitnami's [laravel-env.sh](https://github.com/bitnami/bitnami-docker-laravel/blob/master/9/debian-10/rootfs/opt/bitnami/scripts/laravel-env.sh) the Database configuration.

\#L69 [`export LARAVEL_DATABASE_HOST="${LARAVEL_DATABASE_HOST:-mariadb}"`](https://github.com/bitnami/bitnami-docker-laravel/blob/master/9/debian-10/rootfs/opt/bitnami/scripts/laravel-env.sh#L69)

I've opened an issue to [bitnami-docker-laravel](https://github.com/bitnami/bitnami-docker-laravel/issues/163) to trace the bug.

### 🐛
