### ISSUE TITLE
barryvdh/laravel-ide-helper cant create helpers for Mongodb models

### ISSUE THREAD

**Issue by Dzemy** [jenssegers/laravel-mongodb#2449]
### Versions:
- PHP Version: 8.1.9
- "jenssegers/mongodb": "^3.9",
- "laravel/framework": "^9.19",
- "barryvdh/laravel-ide-helper": "^2.12",

### Description:
Cant create model helpers for models that use mongo db with barryvdh/laravel-ide-helper

I found this thread https://github.com/jenssegers/laravel-mongodb/issues/1785 but there is no answer or solution, how to fix this.

### My testing repo

https://github.com/Dzemy/getDoctrineDriverReplicate.git

### Steps to reproduce
1. Create new laravel project
2. Add jenssegers/mongodb
3. Add barryvdh/laravel-ide-helper
4. Create any model that use mongo connection
5. Run php artisan ide-helper:models --nowrite

### Expected behaviour
Laravel ide helper create  _ide_helper_models.php with mongo models
### Actual behaviour
Excepton for each model that use mongo connection will appear

<details><summary><b>Trace</b>:</summary>

```
Exception: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class MongoDB\Database does not have a method "getDoctrineDriver"
Could not analyze class App\Models\Mongotest.

Trace:

#0 /var/www/html/vendor/jenssegers/mongodb/src/Connection.php(304): call_user_func_array()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1115): Jenssegers\Mongodb\Connection->__call()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1098): Illuminate\Database\Connection->getDoctrineConnection()
#3 /var/www/html/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(467): Illuminate\Database\Connection->getDoctrineSchemaManager()
#4 /var/www/html/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(286): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromTable()
#5 /var/www/html/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(177): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\Container\Container->call()
#12 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\Component\Console\Command\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(1002): Illuminate\Console\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#16 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#19 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#20 {main}
```
</details>

**Comment by GiuPic** [comment]
Hi, sorry if I bring up this issue again, but I get the same message when I run php artisan ide-helper:models --nowrite.
Has anyone solved it by chance?

**Comment by sowich** [comment]
[https://github.com/barryvdh/laravel-ide-helper/issues/590#issuecomment-650407958](url)
