### ISSUE TITLE
Retry closed connections.

### ISSUE THREAD

**Issue by ryansmith94** [jenssegers/laravel-mongodb#508]
We're encountering problems with object rocket and it's replica sets. I hope someone else here has had this issue too.

We think the issue can be solved by retrying the connection (see links below). I'm going to test that retrying the connection does solve the issue for us. If it does, would you be happy for me to make a pull request to wrap the connection attempt in a try-catch and retry? I know it's an edge case, but we need this fixed asap and I don't want to point composer to a forked version of this repo if possible.

http://stackoverflow.com/questions/22399795/mongo-db-connection-problems
https://www.compose.io/articles/achieving-high-availability-and-the-mongodb-php-driver/
https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Connection.php#L153

**Comment by ryansmith94** [comment]
Version: 1.4.3
Error message: Failed to connect to: DELETED:25497: Remote server has closed the connection
Stack trace: 
```
[
  {
    "file":"\/var\/www\/learning_locker\/releases\/be24d6339b19c9bded4e74825214b19432a0903c\/vendor\/jenssegers\/mongodb\/src\/Jenssegers\/Mongodb\/Connection.php",
    "line":0,
    "function":"__construct",
    "class":"MongoClient",
    "type":"->"
  },
  {
    "file":"\/var\/www\/learning_locker\/releases\/be24d6339b19c9bded4e74825214b19432a0903c\/vendor\/jenssegers\/mongodb\/src\/Jenssegers\/Mongodb\/Connection.php",
    "line":40,
    "function":"createConnection",
    "class":"Jenssegers\\Mongodb\\Connection",
    "type":"->",
    "args":[
      "mongodb:\/\/DELETED:25497\/DELETED",
      {
        "driver":"mongodb",
        "host":"DELETED",
        "port":"25497",
        "username":"DELETED",
        "password":"DELETED",
        "database":"DELETED",
        "options":{
          "ssl":true
        }
      },
      {
        "ssl":true
      }
    ]
  },
  {
    "file":"\/var\/www\/learning_locker\/releases\/be24d6339b19c9bded4e74825214b19432a0903c\/vendor\/jenssegers\/mongodb\/src\/Jenssegers\/Mongodb\/MongodbServiceProvider.php",
    "line":19,
    "function":"__construct",
    "class":"Jenssegers\\Mongodb\\Connection",
    "type":"->",
    "args":[
      {
        "driver":"mongodb",
        "host":"DELETED",
        "port":"25497",
        "username":"DELETED",
        "password":"DELETED",
        "database":"DELETED",
        "options":{
          "ssl":true
        }
      }
    ]
  },
  {
    "function":"Jenssegers\\Mongodb\\{closure}",
    "class":"Jenssegers\\Mongodb\\MongodbServiceProvider",
    "type":"->",
    "args":[
      {
        "driver":"mongodb",
        "host":"DELETED",
        "port":"25497",
        "username":"DELETED",
        "password":"DELETED",
        "database":"DELETED",
        "options":{
          "ssl":true
        }
      },
      "mongodb"
    ]
  },
  "DELETED"
]
```

**Comment by ryansmith94** [comment]
Additional research:
https://jira.mongodb.org/browse/PHP-1115
https://jira.mongodb.org/browse/PHP-854

**Comment by madmanlear** [comment]
I experienced the same issue with Object Rocket and found this fix worked perfectly. I would recommend integrating it.

Thanks ryansmith94!

**Comment by ryansmith94** [comment]
You're welcome @madmanlear :-)

**Comment by jenssegers** [comment]
Laravel already has some basic structure set up for automatic reconnecting, but MongoDB can't use it. See `tryAgainIfCausedByLostConnection`.

It might be cool to add something similar for every query being done with automatic reconnect.

**Comment by jenssegers** [comment]
Also, is there a specific exception type that is being thrown? Just catching all Exceptions seems a bit dangerous.

**Comment by madmanlear** [comment]
The exception is "Remote server has closed the connection." The full log is below.

```
[2015-08-18 13:33:57] local.ERROR: exception 'MongoConnectionException' with message 'Failed to connect to: iad-mongos0.objectrocket.com:15109: Remote server has closed the connection' in ~/Sites/site-name/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:153
Stack trace:
#0 ~/Sites/site-name/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php(153): MongoClient->__construct('mongodb://iad-m...', Array, Array)
#1 ~/Sites/site-name/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php(38): Jenssegers\Mongodb\Connection->createConnection('mongodb://iad-m...', Array, Array)
#2 ~/Sites/site-name/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/MongodbServiceProvider.php(30): Jenssegers\Mongodb\Connection->__construct(Array)
#3 [internal function]: Jenssegers\Mongodb\MongodbServiceProvider->Jenssegers\Mongodb\{closure}(Array, 'mongodb')
#4 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(163): call_user_func(Object(Closure), Array, 'mongodb')
#5 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(67): Illuminate\Database\DatabaseManager->makeConnection('mongodb')
#6 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3175): Illuminate\Database\DatabaseManager->connection(NULL)
#7 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3141): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 ~/Sites/site-name/vendor/jenssegers/mongodb/src/Jenssegers/Eloquent/Model.php(276): Illuminate\Database\Eloquent\Model->getConnection()
#9 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1838): Jenssegers\Eloquent\Model->newBaseQueryBuilder()
#10 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1812): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#11 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\Database\Eloquent\Model->newQuery()
#12 ~/Sites/site-name/app/Http/Controllers/PhotoController.php(20): Illuminate\Database\Eloquent\Model::all()
#13 [internal function]: App\Http\Controllers\PhotoController->index()
#14 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#15 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#16 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\PhotoController), Object(Illuminate\Routing\Route), 'index')
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\PhotoController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#23 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/Route.php(201): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'index')
#24 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#25 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 ~/Sites/site-name/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#58 ~/Sites/site-name/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#59 {main}
```

**Comment by ryansmith94** [comment]
Closing because of inactivity.
